function(target_link_runtime target_name project_binary_directory)
    message(STATUS "Copy Immortal Runtime for target - ${target_name}")
    file(COPY ${IMMORTAL_ASSET_DIR} DESTINATION ${project_binary_directory})
    file(COPY ${IMMORTAL_RUNTIME} DESTINATION ${project_binary_directory})
    if (AgilitySDK_SHARED)
        file(COPY ${AgilitySDK_SHARED} DESTINATION ${project_binary_directory}/D3D12)
    endif()
endfunction()
