#pragma once

#include "ImmortalCore.h"

#define IMMORTAL_CONSTANT_STRING_CONSOLE		UNICODE8("调试控制台")
#define IMMORTAL_CONSTANT_STRING_DEMO_CONSOLE	UNICODE8("测试控制台")
#define IMMORTAL_CONSTANT_STRING_RENDER_RATE	UNICODE8("\n渲染效力： %.3f ms / 帧 (%.1f FPS)")

#define IMMORTAL_CONSTANT_STRING_FILE	UNICODE8(" 文件(F) ")
#define IMMORTAL_CONSTANT_STRING_OPEN	UNICODE8("打开")
#define IMMORTAL_CONSTANT_STRING_SAVE	UNICODE8("保存")
#define IMMORTAL_CONSTANT_STRING_EXIT	UNICODE8("退出")
#define IMMORTAL_CONSTANT_STRING_CLOSE	UNICODE8("关闭")

#define IMMORTAL_CONSTANT_STRING_EDIT	UNICODE8(" 编辑(E) ")
#define IMMORTAL_CONSTANT_STRING_VIEW  UNICODE8(" 视图(V) ")
#define IMMORTAL_CONSTANT_STRING_HELP  UNICODE8(" 帮助(H) ")

#define IMMORTAL_CONSTANT_STRING_GRAPHICS  UNICODE8(" 图形(G) ")